# Generated by Django 4.2.16 on 2026-01-26 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified (Awaiting Approval)'), ('active', 'Active'), ('disabled', 'Disabled')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='PatientCaregiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caregiver', models.ForeignKey(limit_choices_to={'role': 'caregiver'}, on_delete=django.db.models.deletion.CASCADE, related_name='patient_links', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='caregiver_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('patient', 'caregiver')},
            },
        ),
    ]
