# Generated by Django 6.0.1 on 2026-01-29 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_patientprofile_consulting_doctor_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='emergency_contact_relation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
