# Generated by Django 4.2.16 on 2026-01-29 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_alert_id_alter_caregiverprofile_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='consulting_doctor_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
