# Generated by Django 4.2.16 on 2026-01-29 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_patientprofile_consulting_doctor_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientcaregiver',
            name='level',
            field=models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary')], default='secondary', max_length=20),
        ),
        migrations.AddField(
            model_name='patientcaregiver',
            name='relationship',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
