# Generated by Django 4.2.16 on 2026-01-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_alert_id_alter_caregiverprofile_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='comfort_items',
            field=models.TextField(blank=True, help_text='e.g. Prayer, music, walking'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='preferred_language',
            field=models.CharField(blank=True, help_text='e.g. Malayalam / English', max_length=100),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='preferred_routine',
            field=models.CharField(blank=True, help_text='e.g. Morning-oriented', max_length=100),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='safety_notes',
            field=models.TextField(blank=True, help_text='Caregiver-only safety warnings'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='sensitivities',
            field=models.TextField(blank=True, help_text='e.g. Loud noises, crowds'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='caregiverprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='patientcaregiver',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='patientmemory',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='routine',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
