# Generated by Django 4.2.16 on 2026-01-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_patientprofile_comfort_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='comfort_items',
            field=models.TextField(blank=True, help_text='e.g. Prayer, music', null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='preferred_language',
            field=models.CharField(blank=True, help_text='e.g. Malayalam / English', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='preferred_routine',
            field=models.CharField(blank=True, help_text='e.g. Morning-oriented', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='safety_notes',
            field=models.TextField(blank=True, help_text='Caregiver-only notes on risks.', null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='sensitivities',
            field=models.TextField(blank=True, help_text='e.g. Loud noises / Crowds', null=True),
        ),
    ]
