# Generated by Django 6.0.1 on 2026-01-31 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_patientprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiverprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
