# Generated by Django 6.0.1 on 2026-01-31 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_caregiverprofile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientcaregiver',
            name='living_arrangement',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
