# Generated by Django 6.0.1 on 2026-01-31 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_patientcaregiver_living_arrangement'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiverprofile',
            name='living_arrangement',
            field=models.CharField(blank=True, choices=[('same_household', 'Same Household'), ('remote', 'Remote / Nearby'), ('facility', 'Assisted Living Facility')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='caregiverprofile',
            name='relationship',
            field=models.CharField(choices=[('spouse', 'Spouse'), ('child', 'Child'), ('family', 'Family Member'), ('professional', 'Professional Caregiver'), ('other', 'Other')], max_length=50),
        ),
    ]
