# Generated by Django 6.0.1 on 2026-01-31 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_caregiverprofile_living_arrangement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caregiverprofile',
            name='relationship',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
