# Generated by Django 6.0.1 on 2026-01-31 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_caregiverprofile_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientcaregiver',
            name='care_context',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patientcaregiver',
            name='consent_basis',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patientcaregiver',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientcaregiver',
            name='risk_lives_alone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientcaregiver',
            name='risk_wandering',
            field=models.BooleanField(default=False),
        ),
    ]
