# Generated by Django 6.0.1 on 2026-01-31 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_patientprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientcaregiver',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='patientcaregiver',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientcaregiver',
            name='approved_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientcaregiver',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
