# Generated by Django 6.0.1 on 2026-02-06 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_routine_days_of_week_alter_alert_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='notes',
            field=models.TextField(blank=True, help_text='Instructions or additional notes for the routine', null=True),
        ),
    ]
