# Generated by Django 4.2.16 on 2026-02-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_routine_alert_interval_routine_escalation_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklog',
            name='alert_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
