# Generated by Django 4.2.16 on 2026-02-06 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_tasklog_alert_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='routine',
            field=models.ForeignKey(blank=True, help_text='Reference to the routine for missed_task alerts', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='users.routine'),
        ),
    ]
