# Generated by Django 4.2.16 on 2026-02-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_alert_routine'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
