# Generated by Django 5.2.11 on 2026-02-10 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_alert_latitude_alert_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
