# Generated by Django 5.2.11 on 2026-02-10 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_routine_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='target_date',
            field=models.DateField(blank=True, help_text='Specific date for one-time routines', null=True),
        ),
        migrations.AlterField(
            model_name='routine',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Every Day'), ('weekly', 'Specific Days'), ('once', 'Specific Date'), ('custom', 'Flexible / Custom')], default='daily', max_length=20),
        ),
    ]
