# Generated by Django 5.2.11 on 2026-02-12 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_routine_target_date_alter_routine_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcmtoken',
            name='token',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='patientcaregiver',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revoked', 'Revoked')], default='pending', max_length=20),
        ),
    ]
